# Dataset
dataset: mnist
dataset_kwargs:
  to_float: true
  image_only: true

# Training config
train_config:
  batch_size: 128
  epochs: 100
  eval_every_n_steps: 500
  summary_every_n_steps: 100
  save_every_n_steps: 1000
  max_ckpts_to_keep: 20
  shuffle_buffer: 50000

# Learning rate
optimizer: adam
learning_rate:
  initial_learning_rate: 0.001
  decay_steps: 1000
  decay_rate: 0.97
  staircase: true

# Network
ae_type: cnn_im

# encoder
encoder_configs:
  - type: Conv2D  # 24
    kernel_size: 5
    strides: 1
    padding: VALID
    filters: 8
    activation: relu
    use_batchnorm: false
    use_bias: true
  - type: Conv2D  # 12
    kernel_size: 3
    strides: 2
    padding: SAME
    filters: 16
    activation: relu
    use_batchnorm: false
    use_bias: true
  - type: Conv2D  # 6
    kernel_size: 3
    strides: 2
    padding: SAME
    filters: 32
    activation: relu
    use_batchnorm: false
    use_bias: true
  - type: Conv2D  # 3
    kernel_size: 3
    strides: 2
    padding: SAME
    filters: 16
    activation: relu
    use_batchnorm: false
    use_bias: true

decoder_kwargs:
    n_vars: 16,
    filters: [32, 16, 8]

load_checkpoint: null
